### ISSUE TITLE
reset

### ISSUE THREAD

**Issue by coderhaoxin** [onebook/scssbase#14]
```css
li {
  list-style: none;
}
```

**Comment by coderhaoxin** [comment]
```css
span {
  display: inline-block;
}
```
