### ISSUE TITLE
mixin: word

### ISSUE THREAD

**Issue by coderhaoxin** [onebook/scssbase#8]
```scss
@mixin word1line() {
  word-break: keep-all;
  white-space: nowrap;
  overflow: hidden;
}
```
